using System;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using DataSense.Database;
using DataSense.Helpers;

namespace DataSense.Services;

public class LinuxStartupService : ILinuxStartupService
{
    private readonly ILinuxStorageService _storageService;
    private readonly ILinuxPlatformService _platformService;
    private readonly INetworkUsageRepository _repository;

    public LinuxStartupService(
        ILinuxStorageService storageService,
        ILinuxPlatformService platformService,
        INetworkUsageRepository repository)
    {
        _storageService  = storageService  ?? throw new ArgumentNullException(nameof(storageService));
        _platformService = platformService ?? throw new ArgumentNullException(nameof(platformService));
        _repository       = repository       ?? throw new ArgumentNullException(nameof(repository));
    }

    public string GetAutostartFilePath()
    {
        return Path.Combine(_storageService.AutostartDirectory, "datasense.desktop");
    }

    public async Task<bool> IsAutostartEnabledAsync()
    {
        string desktopFile = GetAutostartFilePath();
        if (!File.Exists(desktopFile)) return false;

        try
        {
            string content = await File.ReadAllTextAsync(desktopFile);
            return content.Contains("X-GNOME-Autostart-enabled=true", StringComparison.OrdinalIgnoreCase)
                || !content.Contains("X-GNOME-Autostart-enabled=false", StringComparison.OrdinalIgnoreCase);
        }
        catch
        {
            return false;
        }
    }

    public async Task<bool> SetAutostartEnabledAsync(bool enable)
    {
        string desktopFile = GetAutostartFilePath();

        if (!enable)
        {
            try
            {
                if (File.Exists(desktopFile))
                {
                    File.Delete(desktopFile);
                }
                await _repository.SaveSettingAsync("StartAtLogin", "false");
                return true;
            }
            catch
            {
                return false;
            }
        }

        string execPath = GetApplicationExecutablePath();
        if (string.IsNullOrEmpty(execPath)) return false;

        string desktopContent = $@"# Generated by DataSense Desktop Integration
[Desktop Entry]
Type=Application
Name=DataSense
Comment=Local network data usage monitor and analytics
Exec={execPath} --autostart
Icon=datasense
Categories=Network;Utility;
Terminal=false
X-GNOME-Autostart-enabled=true
";

        try
        {
            Directory.CreateDirectory(_storageService.AutostartDirectory);
            await File.WriteAllTextAsync(desktopFile, desktopContent);
            await _repository.SaveSettingAsync("StartAtLogin", "true");
            return true;
        }
        catch
        {
            return false;
        }
    }

    public async Task<bool> VerifyAutostartFileAsync()
    {
        string desktopFile = GetAutostartFilePath();
        if (!File.Exists(desktopFile)) return false;

        try
        {
            string content = await File.ReadAllTextAsync(desktopFile);
            return content.Contains("[Desktop Entry]")
                && content.Contains("Type=Application")
                && content.Contains("Exec=");
        }
        catch
        {
            return false;
        }
    }

    public async Task<bool> IsSystemdUserSessionAvailableAsync()
    {
        return await Task.FromResult(_platformService.HasSystemdUserSession);
    }

    public async Task<bool> SetSystemdUserServiceEnabledAsync(bool enable)
    {
        if (!_platformService.HasSystemdUserSession) return false;

        string systemctlPath = _platformService.GetExecutablePath("systemctl");
        if (string.IsNullOrEmpty(systemctlPath)) return false;

        string execPath = GetApplicationExecutablePath();
        if (string.IsNullOrEmpty(execPath)) return false;

        string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        string userServiceDir = Path.Combine(home, ".config", "systemd", "user");
        string serviceFilePath = Path.Combine(userServiceDir, "datasense.service");

        if (!enable)
        {
            await ProcessExecutionHelper.ExecuteAsync(systemctlPath, new[] { "--user", "disable", "datasense.service" }, timeoutMs: 2000);
            if (File.Exists(serviceFilePath))
            {
                File.Delete(serviceFilePath);
            }
            return true;
        }

        string serviceContent = $@"[Unit]
Description=DataSense Local Network Monitor
After=network.target

[Service]
Type=simple
ExecStart={execPath} --daemon
Restart=on-failure

[Install]
WantedBy=default.target
";

        try
        {
            Directory.CreateDirectory(userServiceDir);
            await File.WriteAllTextAsync(serviceFilePath, serviceContent);
            var reloadRes = await ProcessExecutionHelper.ExecuteAsync(systemctlPath, new[] { "--user", "daemon-reload" }, timeoutMs: 2000);
            var enableRes = await ProcessExecutionHelper.ExecuteAsync(systemctlPath, new[] { "--user", "enable", "datasense.service" }, timeoutMs: 2000);
            return enableRes.Success;
        }
        catch
        {
            return false;
        }
    }

    public static string GetApplicationExecutablePath()
    {
        // 1. Process.GetCurrentProcess().MainModule?.FileName
        try
        {
            string? procPath = Environment.ProcessPath;
            if (!string.IsNullOrWhiteSpace(procPath) && File.Exists(procPath) && !procPath.EndsWith("dotnet", StringComparison.OrdinalIgnoreCase))
            {
                return procPath;
            }
        }
        catch { }

        // 2. Entry assembly location
        try
        {
            string? asmPath = Assembly.GetEntryAssembly()?.Location;
            if (!string.IsNullOrWhiteSpace(asmPath) && File.Exists(asmPath))
            {
                if (asmPath.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
                {
                    string execCandidate = Path.ChangeExtension(asmPath, null);
                    if (File.Exists(execCandidate)) return execCandidate;
                    return $"dotnet {asmPath}";
                }
                return asmPath;
            }
        }
        catch { }

        // 3. Fallback to AppContext BaseDirectory
        string baseDir = AppContext.BaseDirectory;
        string candidate = Path.Combine(baseDir, "DataSense");
        if (File.Exists(candidate)) return candidate;

        return Path.Combine(baseDir, "DataSense.dll");
    }
}
